package com.substring.chat.entities;

import java.time.LocalDateTime;

import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

@Document(collection="files")
public class FileEntity {
  @Id
  private Long id;
  private String fileName;
  private String fileType;
  private String filePath;
  private String fileSize;
  private String fileUrl;
  private LocalDateTime uploadTime;

//   here getter and setter methods are generated by lombok;
}
